version: '3.2'
services:

  pdjam:
    container_name: pdjam
    build: server/
    ports:
      - "5000:5000"
    environment:
      - PROXY=http://proxy:5002
      - PD_HOST=pd
      - PD_PORT=5001
    depends_on:
      - proxy
      - pd

  proxy:
    container_name: proxy
    build: proxy/
    ports:
      - "5002:5002"
    environment:
      - SERVER=localhost:5002

  pd: # pure data service (pd-extended)
    container_name: pd
    build: pd/
    ports:
      - "5001:5001"
